# ------------------------------------------------
# BigQuery Upload
# ------------------------------------------------
bigquery_config:
  project_id: ${BQ_PROJECT_ID}
  dataset: ${BQ_DATASET}
  table: ${BQ_TABLE}
  summary_table: ${BQ_SUMMARY_TABLE}

# ------------------------------------------------
# GeoJSON Config
# ------------------------------------------------
geojson_url: "external/taxi_zones.geojson"

# ------------------------------------------------
# Google Credentials
# ------------------------------------------------
google_application_credentials: ${GOOGLE_APPLICATION_CREDENTIALS_PATH}