[tool.poetry]
name = "nyc-taxi-data-pipeline"
version = "0.1.0"
description = "NYC Yellow Taxi Data Engineering Pipeline with Airflow, BigQuery, Streamlit"
authors = ["Tuo Yang <yangtuomailbox@gmail.com>"]